# Site settings
title: Silver Bullet Club
description: > # this means to ignore newlines until "baseurl:"
  Silver Bullet ClubのWEBサイトです。チームへの仕事の依頼はこちらからどうぞ。
author: Silver Bullet Club
url: https://silver-bullet.club
lang: ja_JP

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      image: /assets/img/silverbulletclub_banner.png
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      image: /assets/img/silverbulletclub_banner.png
  
